// lib/db/migrate.ts
// libsql ベースのスキーマ初期化。
// テーブルが無ければ CREATE する。drizzle-kit を別途実行しなくてもよい。
//
// schema.ts に新しいテーブルを追加したら、ここにも追記する。

import type { Client } from '@libsql/client'

const STATEMENTS = [
  `CREATE TABLE IF NOT EXISTS ohlcv (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    code TEXT NOT NULL,
    market TEXT NOT NULL,
    date TEXT NOT NULL,
    open REAL NOT NULL,
    high REAL NOT NULL,
    low REAL NOT NULL,
    close REAL NOT NULL,
    volume INTEGER NOT NULL,
    adjusted_close REAL,
    source TEXT NOT NULL,
    created_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS hex_stages (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    date TEXT NOT NULL,
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    sector_large TEXT,
    market_cap REAL,
    stage_a INTEGER NOT NULL,
    stage_b INTEGER,
    timeframe TEXT NOT NULL,
    close REAL,
    sma5 REAL,
    sma25 REAL,
    sma75 REAL,
    rsi14 REAL,
    macd REAL,
    created_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS tv_indicators (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    code TEXT NOT NULL,
    date TEXT NOT NULL,
    timeframe TEXT NOT NULL,
    close REAL,
    sma5 REAL,
    sma25 REAL,
    sma75 REAL,
    sma200 REAL,
    ema5 REAL,
    ema25 REAL,
    rsi14 REAL,
    macd REAL,
    macd_signal REAL,
    macd_histogram REAL,
    bb_upper REAL,
    bb_middle REAL,
    bb_lower REAL,
    volume INTEGER,
    volume_ratio REAL,
    source TEXT NOT NULL,
    created_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS tv_daily_snapshots (
    date TEXT NOT NULL,
    ticker TEXT NOT NULL,
    name TEXT NOT NULL,
    price REAL,
    currency TEXT,
    change_percent_1d REAL,
    volume_1d INTEGER,
    avg_volume_10d INTEGER,
    avg_volume_30d INTEGER,
    market_cap REAL,
    market_cap_currency TEXT,
    perf_pct_1w REAL,
    perf_pct_1m REAL,
    perf_pct_3m REAL,
    perf_pct_6m REAL,
    perf_pct_ytd REAL,
    sma_5d REAL,
    sma_25d REAL,
    sma_75d REAL,
    sma_150d REAL,
    sma_300d REAL,
    sma_5w REAL,
    sma_13w REAL,
    sma_25w REAL,
    sma_50w REAL,
    sma_100w REAL,
    sma_3m REAL,
    sma_5m REAL,
    sma_10m REAL,
    sma_20m REAL,
    sma_25m REAL,
    earnings_last_date TEXT,
    earnings_next_date TEXT,
    imported_at TEXT NOT NULL,
    source_file TEXT,
    PRIMARY KEY (date, ticker)
  )`,
  `CREATE INDEX IF NOT EXISTS idx_tv_snapshots_ticker ON tv_daily_snapshots(ticker)`,
  `CREATE INDEX IF NOT EXISTS idx_tv_snapshots_earnings_next ON tv_daily_snapshots(earnings_next_date)`,
  `CREATE TABLE IF NOT EXISTS csv_imports (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    date TEXT NOT NULL,
    file_name TEXT NOT NULL,
    row_count INTEGER NOT NULL,
    imported_at TEXT NOT NULL,
    detection_method TEXT
  )`,
  `CREATE TABLE IF NOT EXISTS sector_master (
    ticker TEXT PRIMARY KEY,
    name TEXT,
    sector_large TEXT,
    sector_small TEXT,
    updated_at TEXT NOT NULL,
    source_file TEXT
  )`,
  // ─── Phase 2: 銘柄ユニバース ───
  `CREATE TABLE IF NOT EXISTS ticker_universe (
    ticker TEXT PRIMARY KEY,
    name TEXT,
    active INTEGER NOT NULL DEFAULT 1,
    added_at INTEGER NOT NULL DEFAULT (unixepoch())
  )`,
  `CREATE TABLE IF NOT EXISTS historical_universe (
    ticker TEXT PRIMARY KEY,
    name TEXT,
    first_trade_date TEXT NOT NULL,
    last_trade_date TEXT NOT NULL,
    trading_days INTEGER NOT NULL DEFAULT 0,
    latest_ohlcv_date TEXT NOT NULL,
    is_latest_member INTEGER NOT NULL DEFAULT 0,
    status TEXT NOT NULL,
    missing_from_ticker_universe INTEGER NOT NULL DEFAULT 0,
    market_segment TEXT,
    sector17_code TEXT,
    sector17_name TEXT,
    sector33_code TEXT,
    sector33_name TEXT,
    margin_type TEXT,
    ohlcv_rows INTEGER NOT NULL DEFAULT 0,
    ml_physics_v2_rows INTEGER NOT NULL DEFAULT 0,
    has_ml_physics_v2 INTEGER NOT NULL DEFAULT 0,
    source TEXT NOT NULL DEFAULT 'ohlcv_daily',
    payload_json TEXT NOT NULL DEFAULT '{}',
    computed_at INTEGER NOT NULL DEFAULT (unixepoch())
  )`,
  `CREATE INDEX IF NOT EXISTS historical_universe_status_idx ON historical_universe(status, last_trade_date)`,
  `CREATE INDEX IF NOT EXISTS historical_universe_latest_idx ON historical_universe(is_latest_member, last_trade_date)`,
  `CREATE TABLE IF NOT EXISTS historical_universe_audits (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    run_started_at INTEGER NOT NULL,
    latest_ohlcv_date TEXT,
    ohlcv_ticker_count INTEGER NOT NULL DEFAULT 0,
    latest_member_count INTEGER NOT NULL DEFAULT 0,
    historical_only_count INTEGER NOT NULL DEFAULT 0,
    missing_ticker_universe_count INTEGER NOT NULL DEFAULT 0,
    ml_feature_complete_count INTEGER NOT NULL DEFAULT 0,
    ml_feature_incomplete_count INTEGER NOT NULL DEFAULT 0,
    ohlcv_row_count INTEGER NOT NULL DEFAULT 0,
    ml_feature_row_count INTEGER NOT NULL DEFAULT 0,
    status TEXT NOT NULL,
    payload_json TEXT NOT NULL,
    computed_at INTEGER NOT NULL DEFAULT (unixepoch())
  )`,
  // ─── Phase 2: 日足 OHLCV 履歴 ───
  `CREATE TABLE IF NOT EXISTS ohlcv_daily (
    ticker TEXT NOT NULL,
    date TEXT NOT NULL,
    open REAL NOT NULL,
    high REAL NOT NULL,
    low REAL NOT NULL,
    close REAL NOT NULL,
    volume INTEGER NOT NULL,
    PRIMARY KEY (ticker, date)
  )`,
  `CREATE INDEX IF NOT EXISTS ohlcv_date_idx ON ohlcv_daily(date)`,
  `CREATE INDEX IF NOT EXISTS ohlcv_date_ticker_idx ON ohlcv_daily(date, ticker)`,
  `CREATE TABLE IF NOT EXISTS manual_ohlcv_daily (
    market TEXT NOT NULL DEFAULT 'JP',
    ticker TEXT NOT NULL,
    date TEXT NOT NULL,
    open REAL NOT NULL,
    high REAL NOT NULL,
    low REAL NOT NULL,
    close REAL NOT NULL,
    volume INTEGER NOT NULL DEFAULT 0,
    source_name TEXT,
    source_note TEXT,
    imported_at INTEGER NOT NULL DEFAULT (unixepoch()),
    PRIMARY KEY (market, ticker, date)
  )`,
  `CREATE INDEX IF NOT EXISTS manual_ohlcv_market_ticker_date_idx ON manual_ohlcv_daily(market, ticker, date)`,
  `CREATE TABLE IF NOT EXISTS market_universe (
    market TEXT NOT NULL,
    ticker TEXT NOT NULL,
    name TEXT,
    active INTEGER NOT NULL DEFAULT 1,
    exchange TEXT,
    currency TEXT,
    asset_type TEXT,
    sector TEXT,
    industry TEXT,
    start_date TEXT,
    end_date TEXT,
    shares_outstanding INTEGER,
    source TEXT NOT NULL,
    source_payload_json TEXT NOT NULL DEFAULT '{}',
    updated_at INTEGER NOT NULL DEFAULT (unixepoch()),
    PRIMARY KEY (market, ticker)
  )`,
  `CREATE INDEX IF NOT EXISTS market_universe_market_active_idx ON market_universe(market, active, ticker)`,
  `CREATE INDEX IF NOT EXISTS market_universe_market_name_idx ON market_universe(market, name)`,
  `CREATE TABLE IF NOT EXISTS market_classifications (
    market TEXT NOT NULL,
    ticker TEXT NOT NULL,
    taxonomy TEXT NOT NULL,
    effective_from TEXT NOT NULL DEFAULT '0000-01-01',
    effective_to TEXT,
    sector_code TEXT,
    sector_name TEXT,
    industry_code TEXT,
    industry_name TEXT,
    source TEXT NOT NULL,
    confidence REAL NOT NULL DEFAULT 1,
    raw_json TEXT NOT NULL DEFAULT '{}',
    updated_at INTEGER NOT NULL DEFAULT (unixepoch()),
    PRIMARY KEY (market, ticker, taxonomy, effective_from)
  )`,
  `CREATE INDEX IF NOT EXISTS market_classifications_taxonomy_sector_idx ON market_classifications(market, taxonomy, sector_name, ticker)`,
  `CREATE INDEX IF NOT EXISTS market_classifications_taxonomy_industry_idx ON market_classifications(market, taxonomy, industry_name, ticker)`,
  `CREATE INDEX IF NOT EXISTS market_classifications_ticker_idx ON market_classifications(market, ticker)`,
  `CREATE TABLE IF NOT EXISTS market_ohlcv_daily (
    market TEXT NOT NULL,
    ticker TEXT NOT NULL,
    date TEXT NOT NULL,
    open REAL NOT NULL,
    high REAL NOT NULL,
    low REAL NOT NULL,
    close REAL NOT NULL,
    adj_open REAL,
    adj_high REAL,
    adj_low REAL,
    adj_close REAL,
    volume INTEGER NOT NULL,
    adj_volume INTEGER,
    div_cash REAL,
    split_factor REAL,
    source TEXT NOT NULL,
    imported_at INTEGER NOT NULL DEFAULT (unixepoch()),
    PRIMARY KEY (market, ticker, date)
  )`,
  `CREATE INDEX IF NOT EXISTS market_ohlcv_market_date_idx ON market_ohlcv_daily(market, date)`,
  `CREATE INDEX IF NOT EXISTS market_ohlcv_market_date_ticker_idx ON market_ohlcv_daily(market, date, ticker)`,
  `CREATE INDEX IF NOT EXISTS market_ohlcv_market_ticker_date_idx ON market_ohlcv_daily(market, ticker, date)`,
  `CREATE TABLE IF NOT EXISTS market_daily_snapshots (
    market TEXT NOT NULL,
    ticker TEXT NOT NULL,
    date TEXT NOT NULL,
    ma_5 REAL,
    ma_25 REAL,
    ma_75 REAL,
    ma_150 REAL,
    ma_300 REAL,
    weekly_ma_5 REAL,
    weekly_ma_13 REAL,
    weekly_ma_25 REAL,
    weekly_ma_50 REAL,
    weekly_ma_100 REAL,
    monthly_ma_3 REAL,
    monthly_ma_5 REAL,
    monthly_ma_10 REAL,
    monthly_ma_20 REAL,
    monthly_ma_25 REAL,
    daily_a_stage INTEGER,
    daily_b_stage INTEGER,
    weekly_a_stage INTEGER,
    weekly_b_stage INTEGER,
    monthly_a_stage INTEGER,
    monthly_b_stage INTEGER,
    prev_close REAL,
    close_5d REAL,
    close_20d REAL,
    close_60d REAL,
    close_120d REAL,
    avg_volume_20 REAL,
    ma_200 REAL,
    ma_200_prev REAL,
    ma_200_observations INTEGER,
    computed_at INTEGER NOT NULL DEFAULT (unixepoch()),
    PRIMARY KEY (market, ticker, date)
  )`,
  `CREATE INDEX IF NOT EXISTS market_snapshots_market_date_idx ON market_daily_snapshots(market, date)`,
  `CREATE INDEX IF NOT EXISTS market_snapshots_market_date_ticker_idx ON market_daily_snapshots(market, date, ticker)`,
  `CREATE INDEX IF NOT EXISTS market_snapshots_market_stage_idx ON market_daily_snapshots(
    market, daily_a_stage, daily_b_stage, weekly_a_stage, weekly_b_stage, monthly_a_stage, monthly_b_stage, date, ticker
  )`,
  `CREATE TABLE IF NOT EXISTS physical_momentum_metrics (
    market TEXT NOT NULL DEFAULT 'JP',
    symbol TEXT NOT NULL,
    date TEXT NOT NULL,
    velocity REAL,
    acceleration REAL,
    momentum REAL,
    force REAL,
    ma5_angle REAL,
    ma25_angle REAL,
    ma75_angle REAL,
    ma200_angle REAL,
    ma_angle_avg REAL,
    energy REAL,
    z_velocity REAL,
    z_acceleration REAL,
    z_momentum REAL,
    z_force REAL,
    z_ma_angle_avg REAL,
    z_energy REAL,
    physical_momentum_score REAL,
    physical_force_score REAL,
    physical_energy_score REAL,
    created_at INTEGER NOT NULL DEFAULT (unixepoch()),
    updated_at INTEGER NOT NULL DEFAULT (unixepoch()),
    PRIMARY KEY (market, symbol, date)
  )`,
  `CREATE INDEX IF NOT EXISTS physical_momentum_market_date_idx ON physical_momentum_metrics(market, date)`,
  `CREATE INDEX IF NOT EXISTS physical_momentum_market_score_idx ON physical_momentum_metrics(market, date, physical_momentum_score)`,
  `CREATE INDEX IF NOT EXISTS physical_momentum_symbol_date_idx ON physical_momentum_metrics(market, symbol, date)`,
  `CREATE TABLE IF NOT EXISTS trade_scenarios (
    id TEXT PRIMARY KEY,
    ticker TEXT NOT NULL,
    market TEXT NOT NULL DEFAULT 'JP',
    name TEXT,
    direction TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'open',
    confidence TEXT NOT NULL DEFAULT 'medium',
    anchor_date TEXT NOT NULL,
    anchor_close REAL,
    horizon_days INTEGER NOT NULL,
    entry_plan_price REAL,
    target_price REAL,
    stop_loss_price REAL,
    thesis TEXT NOT NULL,
    invalidation TEXT,
    review_memo TEXT,
    selected_start_date TEXT,
    selected_end_date TEXT,
    source_range_label TEXT,
    context_json TEXT NOT NULL DEFAULT '{}',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS trade_scenarios_ticker_updated_idx ON trade_scenarios(market, ticker, updated_at)`,
  `CREATE INDEX IF NOT EXISTS trade_scenarios_status_idx ON trade_scenarios(status, updated_at)`,
  `CREATE INDEX IF NOT EXISTS trade_scenarios_anchor_idx ON trade_scenarios(market, ticker, anchor_date)`,
  `CREATE TABLE IF NOT EXISTS api_serving_cache (
    namespace TEXT NOT NULL,
    cache_key TEXT NOT NULL,
    payload_json TEXT NOT NULL,
    generated_at_ms INTEGER NOT NULL,
    expires_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    PRIMARY KEY (namespace, cache_key)
  )`,
  `CREATE INDEX IF NOT EXISTS api_serving_cache_expires_idx
    ON api_serving_cache(namespace, expires_at)`,
  `CREATE TABLE IF NOT EXISTS market_data_runs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    market TEXT NOT NULL,
    job_type TEXT NOT NULL,
    status TEXT NOT NULL,
    started_at INTEGER NOT NULL DEFAULT (unixepoch()),
    finished_at INTEGER,
    total_tickers INTEGER NOT NULL DEFAULT 0,
    succeeded INTEGER NOT NULL DEFAULT 0,
    failed INTEGER NOT NULL DEFAULT 0,
    rows_inserted INTEGER NOT NULL DEFAULT 0,
    error_summary TEXT,
    payload_json TEXT NOT NULL DEFAULT '{}'
  )`,
  `CREATE INDEX IF NOT EXISTS market_data_runs_latest_idx ON market_data_runs(market, job_type, started_at)`,
  `CREATE TABLE IF NOT EXISTS market_earnings_calendar (
    market TEXT NOT NULL,
    ticker TEXT NOT NULL,
    report_date TEXT NOT NULL,
    hour TEXT,
    time_bucket TEXT,
    fiscal_year INTEGER,
    fiscal_quarter INTEGER,
    eps_estimate REAL,
    eps_actual REAL,
    revenue_estimate REAL,
    revenue_actual REAL,
    source TEXT NOT NULL,
    source_url TEXT,
    raw_json TEXT NOT NULL DEFAULT '{}',
    imported_at INTEGER NOT NULL DEFAULT (unixepoch()),
    PRIMARY KEY (market, ticker, report_date)
  )`,
  `CREATE INDEX IF NOT EXISTS market_earnings_market_date_idx
    ON market_earnings_calendar(market, report_date, ticker)`,
  `CREATE INDEX IF NOT EXISTS market_earnings_market_ticker_date_idx
    ON market_earnings_calendar(market, ticker, report_date)`,
  `CREATE INDEX IF NOT EXISTS market_earnings_market_bucket_date_idx
    ON market_earnings_calendar(market, time_bucket, report_date)`,
  `CREATE TABLE IF NOT EXISTS sector_etf_holdings (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    etf_ticker TEXT NOT NULL,
    holding_ticker TEXT NOT NULL,
    holding_name TEXT NOT NULL,
    weight_pct REAL,
    shares REAL,
    market_value REAL,
    as_of_date TEXT,
    source TEXT NOT NULL,
    source_url TEXT,
    raw_json TEXT NOT NULL DEFAULT '{}',
    updated_at INTEGER NOT NULL DEFAULT (unixepoch())
  )`,
  `CREATE INDEX IF NOT EXISTS sector_etf_holdings_etf_weight_idx ON sector_etf_holdings(etf_ticker, weight_pct)`,
  `CREATE INDEX IF NOT EXISTS sector_etf_holdings_ticker_idx ON sector_etf_holdings(holding_ticker)`,
  `CREATE INDEX IF NOT EXISTS sector_etf_holdings_as_of_idx ON sector_etf_holdings(etf_ticker, as_of_date)`,
  `CREATE TABLE IF NOT EXISTS sector_etf_holding_runs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    etf_ticker TEXT NOT NULL,
    source TEXT NOT NULL,
    status TEXT NOT NULL,
    started_at INTEGER NOT NULL DEFAULT (unixepoch()),
    finished_at INTEGER,
    holdings_count INTEGER NOT NULL DEFAULT 0,
    error_summary TEXT,
    source_url TEXT,
    payload_json TEXT NOT NULL DEFAULT '{}'
  )`,
  `CREATE INDEX IF NOT EXISTS sector_etf_holding_runs_latest_idx ON sector_etf_holding_runs(etf_ticker, started_at)`,
  `CREATE INDEX IF NOT EXISTS sector_etf_holding_runs_status_idx ON sector_etf_holding_runs(status, started_at)`,
  `CREATE TABLE IF NOT EXISTS jquants_daily_coverage (
    date TEXT PRIMARY KEY,
    expected_rows INTEGER NOT NULL,
    imported_at INTEGER NOT NULL DEFAULT (unixepoch())
  )`,
  `CREATE TABLE IF NOT EXISTS update_locks (
    job_type TEXT PRIMARY KEY,
    status TEXT NOT NULL,
    owner TEXT,
    started_at INTEGER NOT NULL DEFAULT (unixepoch()),
    heartbeat_at INTEGER NOT NULL DEFAULT (unixepoch()),
    lease_expires_at INTEGER NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS jquants_sync_runs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    target_date TEXT NOT NULL,
    api_type TEXT NOT NULL,
    expected_rows INTEGER NOT NULL DEFAULT 0,
    imported_rows INTEGER NOT NULL DEFAULT 0,
    missing_tickers TEXT,
    status TEXT NOT NULL,
    started_at INTEGER NOT NULL DEFAULT (unixepoch()),
    finished_at INTEGER,
    error_summary TEXT
  )`,
  `CREATE INDEX IF NOT EXISTS jquants_sync_target_idx ON jquants_sync_runs(target_date, api_type)`,
  `CREATE TABLE IF NOT EXISTS compute_state (
    job_type TEXT NOT NULL,
    ticker TEXT NOT NULL,
    last_processed_date TEXT,
    updated_at INTEGER NOT NULL DEFAULT (unixepoch()),
    PRIMARY KEY (job_type, ticker)
  )`,
  `CREATE INDEX IF NOT EXISTS compute_state_job_date_idx ON compute_state(job_type, last_processed_date)`,
  `CREATE TABLE IF NOT EXISTS dashboard_cache (
    date TEXT PRIMARY KEY,
    payload_json TEXT NOT NULL,
    computed_at INTEGER NOT NULL DEFAULT (unixepoch())
  )`,
  `CREATE TABLE IF NOT EXISTS dashboard_trade_signal_cache (
    cache_key TEXT PRIMARY KEY,
    payload_json TEXT NOT NULL,
    computed_at INTEGER NOT NULL DEFAULT (unixepoch())
  )`,
  `CREATE INDEX IF NOT EXISTS dashboard_trade_signal_cache_computed_idx ON dashboard_trade_signal_cache(computed_at DESC)`,
  `CREATE TABLE IF NOT EXISTS dashboard_earnings_alert_cache (
    cache_key TEXT PRIMARY KEY,
    payload_json TEXT NOT NULL,
    computed_at INTEGER NOT NULL DEFAULT (unixepoch())
  )`,
  `CREATE INDEX IF NOT EXISTS dashboard_earnings_alert_cache_computed_idx ON dashboard_earnings_alert_cache(computed_at DESC)`,
  `CREATE TABLE IF NOT EXISTS kabutan_material_news (
    article_id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    published_at TEXT NOT NULL,
    url TEXT NOT NULL,
    category TEXT NOT NULL DEFAULT '材料',
    snippet TEXT,
    related_tickers_json TEXT NOT NULL DEFAULT '[]',
    related_stocks_json TEXT NOT NULL DEFAULT '[]',
    source TEXT NOT NULL DEFAULT 'kabutan',
    fetched_at INTEGER NOT NULL DEFAULT (unixepoch()),
    parse_status TEXT NOT NULL DEFAULT 'ok',
    error_summary TEXT
  )`,
  `CREATE INDEX IF NOT EXISTS kabutan_material_news_published_idx ON kabutan_material_news(published_at DESC)`,
  `CREATE INDEX IF NOT EXISTS kabutan_material_news_status_idx ON kabutan_material_news(parse_status, fetched_at DESC)`,
  `CREATE TABLE IF NOT EXISTS kabutan_material_news_runs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    status TEXT NOT NULL,
    started_at INTEGER NOT NULL DEFAULT (unixepoch()),
    finished_at INTEGER,
    fetched_count INTEGER NOT NULL DEFAULT 0,
    saved_count INTEGER NOT NULL DEFAULT 0,
    error_summary TEXT
  )`,
  `CREATE INDEX IF NOT EXISTS kabutan_material_news_runs_latest_idx ON kabutan_material_news_runs(started_at DESC)`,
  `CREATE TABLE IF NOT EXISTS kabutan_themes (
    theme_id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    rank INTEGER,
    ranking_period TEXT NOT NULL DEFAULT '3days_access',
    ranking_as_of TEXT,
    url TEXT NOT NULL,
    description TEXT,
    representative_stocks_json TEXT NOT NULL DEFAULT '[]',
    related_stocks_json TEXT NOT NULL DEFAULT '[]',
    stock_count INTEGER,
    source TEXT NOT NULL DEFAULT 'kabutan',
    fetched_at INTEGER NOT NULL DEFAULT (unixepoch()),
    parse_status TEXT NOT NULL DEFAULT 'ok',
    error_summary TEXT
  )`,
  `CREATE INDEX IF NOT EXISTS kabutan_themes_rank_idx ON kabutan_themes(rank, fetched_at DESC)`,
  `CREATE INDEX IF NOT EXISTS kabutan_themes_status_idx ON kabutan_themes(parse_status, fetched_at DESC)`,
  `CREATE TABLE IF NOT EXISTS kabutan_theme_runs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    status TEXT NOT NULL,
    started_at INTEGER NOT NULL DEFAULT (unixepoch()),
    finished_at INTEGER,
    fetched_count INTEGER NOT NULL DEFAULT 0,
    saved_count INTEGER NOT NULL DEFAULT 0,
    error_summary TEXT
  )`,
  `CREATE INDEX IF NOT EXISTS kabutan_theme_runs_latest_idx ON kabutan_theme_runs(started_at DESC)`,
  `CREATE TABLE IF NOT EXISTS serving_daily_snapshot_dates (
    date TEXT PRIMARY KEY,
    tickers INTEGER NOT NULL,
    computed_at INTEGER NOT NULL DEFAULT (unixepoch())
  )`,
  // ─── Phase 2: 日次スナップショット (MA + ステージ) ───
  `CREATE TABLE IF NOT EXISTS daily_snapshots (
    ticker TEXT NOT NULL,
    date TEXT NOT NULL,
    ma_5 REAL,
    ma_25 REAL,
    ma_75 REAL,
    ma_150 REAL,
    ma_300 REAL,
    weekly_ma_5 REAL,
    weekly_ma_13 REAL,
    weekly_ma_25 REAL,
    weekly_ma_50 REAL,
    weekly_ma_100 REAL,
    monthly_ma_3 REAL,
    monthly_ma_5 REAL,
    monthly_ma_10 REAL,
    monthly_ma_20 REAL,
    monthly_ma_25 REAL,
    daily_a_stage INTEGER,
    daily_b_stage INTEGER,
    weekly_a_stage INTEGER,
    weekly_b_stage INTEGER,
    monthly_a_stage INTEGER,
    monthly_b_stage INTEGER,
    computed_at INTEGER NOT NULL DEFAULT (unixepoch()),
    PRIMARY KEY (ticker, date)
  )`,
  `CREATE INDEX IF NOT EXISTS snapshots_date_idx ON daily_snapshots(date)`,
  `CREATE INDEX IF NOT EXISTS snapshots_date_ticker_idx ON daily_snapshots(date, ticker)`,
  `CREATE INDEX IF NOT EXISTS snapshots_stage_pattern_idx ON daily_snapshots(
    daily_a_stage, daily_b_stage, weekly_a_stage, weekly_b_stage, monthly_a_stage, monthly_b_stage, date, ticker
  )`,
  `CREATE TABLE IF NOT EXISTS ma25m_monitor_daily (
    ticker TEXT NOT NULL,
    date TEXT NOT NULL,
    close REAL NOT NULL,
    ma25m REAL NOT NULL,
    distance_pct REAL NOT NULL,
    abs_distance_pct REAL NOT NULL,
    distance_1d_pct REAL,
    distance_3d_pct REAL,
    distance_5d_pct REAL,
    distance_10d_pct REAL,
    distance_20d_pct REAL,
    position_side TEXT NOT NULL,
    is_approaching INTEGER NOT NULL DEFAULT 0,
    approach_direction TEXT NOT NULL DEFAULT 'none',
    approach_speed_pct_per_day REAL NOT NULL DEFAULT 0,
    approach_consistency REAL NOT NULL DEFAULT 0,
    distance_shrink_5_pct REAL,
    distance_shrink_10_pct REAL,
    is_contact_default INTEGER NOT NULL DEFAULT 0,
    is_touch INTEGER NOT NULL DEFAULT 0,
    last_touch_date TEXT,
    touch_age_sessions INTEGER,
    cross_direction TEXT,
    last_cross_date TEXT,
    last_cross_direction TEXT,
    cross_age_sessions INTEGER,
    primary_status TEXT NOT NULL,
    closeness_score REAL NOT NULL,
    movement_score REAL NOT NULL,
    event_score REAL NOT NULL,
    approach_score REAL NOT NULL,
    is_rapid_approach INTEGER NOT NULL DEFAULT 0,
    computed_at INTEGER NOT NULL DEFAULT (unixepoch()),
    PRIMARY KEY (ticker, date)
  )`,
  `CREATE INDEX IF NOT EXISTS ma25m_monitor_date_score_idx ON ma25m_monitor_daily(date, approach_score)`,
  `CREATE INDEX IF NOT EXISTS ma25m_monitor_date_distance_idx ON ma25m_monitor_daily(date, abs_distance_pct)`,
  `CREATE INDEX IF NOT EXISTS ma25m_monitor_date_approach_idx ON ma25m_monitor_daily(date, is_approaching, approach_score)`,
  `CREATE INDEX IF NOT EXISTS ma25m_monitor_ticker_date_idx ON ma25m_monitor_daily(ticker, date)`,
  `CREATE TABLE IF NOT EXISTS ma25m_monitor_latest (
    ticker TEXT PRIMARY KEY,
    date TEXT NOT NULL,
    close REAL NOT NULL,
    ma25m REAL NOT NULL,
    distance_pct REAL NOT NULL,
    abs_distance_pct REAL NOT NULL,
    distance_1d_pct REAL,
    distance_3d_pct REAL,
    distance_5d_pct REAL,
    distance_10d_pct REAL,
    distance_20d_pct REAL,
    position_side TEXT NOT NULL,
    is_approaching INTEGER NOT NULL DEFAULT 0,
    approach_direction TEXT NOT NULL DEFAULT 'none',
    approach_speed_pct_per_day REAL NOT NULL DEFAULT 0,
    approach_consistency REAL NOT NULL DEFAULT 0,
    distance_shrink_5_pct REAL,
    distance_shrink_10_pct REAL,
    is_contact_default INTEGER NOT NULL DEFAULT 0,
    is_touch INTEGER NOT NULL DEFAULT 0,
    last_touch_date TEXT,
    touch_age_sessions INTEGER,
    cross_direction TEXT,
    last_cross_date TEXT,
    last_cross_direction TEXT,
    cross_age_sessions INTEGER,
    primary_status TEXT NOT NULL,
    closeness_score REAL NOT NULL,
    movement_score REAL NOT NULL,
    event_score REAL NOT NULL,
    approach_score REAL NOT NULL,
    is_rapid_approach INTEGER NOT NULL DEFAULT 0,
    computed_at INTEGER NOT NULL DEFAULT (unixepoch())
  )`,
  `CREATE INDEX IF NOT EXISTS ma25m_latest_date_score_idx ON ma25m_monitor_latest(date, approach_score)`,
  `CREATE INDEX IF NOT EXISTS ma25m_latest_date_distance_idx ON ma25m_monitor_latest(date, abs_distance_pct)`,
  `CREATE INDEX IF NOT EXISTS ma25m_latest_date_approach_idx ON ma25m_monitor_latest(date, is_approaching, approach_score)`,
  `CREATE TABLE IF NOT EXISTS monthly_ma_monitor_daily (
    ticker TEXT NOT NULL, period INTEGER NOT NULL, date TEXT NOT NULL,
    close REAL NOT NULL, ma_value REAL NOT NULL,
    distance_pct REAL NOT NULL, abs_distance_pct REAL NOT NULL,
    distance_1d_pct REAL, distance_3d_pct REAL, distance_5d_pct REAL,
    distance_10d_pct REAL, distance_20d_pct REAL,
    position_side TEXT NOT NULL,
    is_approaching INTEGER NOT NULL DEFAULT 0,
    approach_direction TEXT NOT NULL DEFAULT 'none',
    approach_speed_pct_per_day REAL NOT NULL DEFAULT 0,
    approach_consistency REAL NOT NULL DEFAULT 0,
    distance_shrink_5_pct REAL, distance_shrink_10_pct REAL,
    is_contact_default INTEGER NOT NULL DEFAULT 0,
    is_touch INTEGER NOT NULL DEFAULT 0,
    last_touch_date TEXT, touch_age_sessions INTEGER,
    cross_direction TEXT, last_cross_date TEXT,
    last_cross_direction TEXT, cross_age_sessions INTEGER,
    primary_status TEXT NOT NULL,
    closeness_score REAL NOT NULL, movement_score REAL NOT NULL,
    event_score REAL NOT NULL, approach_score REAL NOT NULL,
    is_rapid_approach INTEGER NOT NULL DEFAULT 0,
    computed_at INTEGER NOT NULL DEFAULT (unixepoch()),
    PRIMARY KEY (ticker, period, date)
  )`,
  `CREATE INDEX IF NOT EXISTS monthly_ma_monitor_date_period_score_idx ON monthly_ma_monitor_daily(date, period, approach_score)`,
  `CREATE INDEX IF NOT EXISTS monthly_ma_monitor_date_period_distance_idx ON monthly_ma_monitor_daily(date, period, abs_distance_pct)`,
  `CREATE INDEX IF NOT EXISTS monthly_ma_monitor_ticker_period_date_idx ON monthly_ma_monitor_daily(ticker, period, date)`,
  `CREATE TABLE IF NOT EXISTS monthly_ma_monitor_latest (
    ticker TEXT NOT NULL, period INTEGER NOT NULL, date TEXT NOT NULL,
    close REAL NOT NULL, ma_value REAL NOT NULL,
    distance_pct REAL NOT NULL, abs_distance_pct REAL NOT NULL,
    distance_1d_pct REAL, distance_3d_pct REAL, distance_5d_pct REAL,
    distance_10d_pct REAL, distance_20d_pct REAL,
    position_side TEXT NOT NULL,
    is_approaching INTEGER NOT NULL DEFAULT 0,
    approach_direction TEXT NOT NULL DEFAULT 'none',
    approach_speed_pct_per_day REAL NOT NULL DEFAULT 0,
    approach_consistency REAL NOT NULL DEFAULT 0,
    distance_shrink_5_pct REAL, distance_shrink_10_pct REAL,
    is_contact_default INTEGER NOT NULL DEFAULT 0,
    is_touch INTEGER NOT NULL DEFAULT 0,
    last_touch_date TEXT, touch_age_sessions INTEGER,
    cross_direction TEXT, last_cross_date TEXT,
    last_cross_direction TEXT, cross_age_sessions INTEGER,
    primary_status TEXT NOT NULL,
    closeness_score REAL NOT NULL, movement_score REAL NOT NULL,
    event_score REAL NOT NULL, approach_score REAL NOT NULL,
    is_rapid_approach INTEGER NOT NULL DEFAULT 0,
    computed_at INTEGER NOT NULL DEFAULT (unixepoch()),
    PRIMARY KEY (ticker, period)
  )`,
  `CREATE INDEX IF NOT EXISTS monthly_ma_latest_date_period_score_idx ON monthly_ma_monitor_latest(date, period, approach_score)`,
  `CREATE INDEX IF NOT EXISTS monthly_ma_latest_date_period_distance_idx ON monthly_ma_monitor_latest(date, period, abs_distance_pct)`,
  `CREATE TABLE IF NOT EXISTS monthly_ma_cluster_daily (
    ticker TEXT NOT NULL, cluster_key TEXT NOT NULL, date TEXT NOT NULL,
    periods_json TEXT NOT NULL, period_count INTEGER NOT NULL,
    cluster_type TEXT NOT NULL, is_strong INTEGER NOT NULL DEFAULT 0,
    band_low REAL NOT NULL, band_high REAL NOT NULL,
    band_average REAL NOT NULL, spread_pct REAL NOT NULL,
    close REAL NOT NULL, distance_pct REAL NOT NULL, abs_distance_pct REAL NOT NULL,
    approach_direction TEXT NOT NULL DEFAULT 'none',
    is_approaching INTEGER NOT NULL DEFAULT 0,
    approach_speed_pct_per_day REAL NOT NULL DEFAULT 0,
    is_touch INTEGER NOT NULL DEFAULT 0,
    last_touch_date TEXT, touch_age_sessions INTEGER,
    cross_direction TEXT, last_cross_date TEXT,
    last_cross_direction TEXT, cross_age_sessions INTEGER,
    primary_status TEXT NOT NULL, approach_score REAL NOT NULL,
    computed_at INTEGER NOT NULL DEFAULT (unixepoch()),
    PRIMARY KEY (ticker, cluster_key, date)
  )`,
  `CREATE INDEX IF NOT EXISTS monthly_ma_cluster_date_score_idx ON monthly_ma_cluster_daily(date, approach_score)`,
  `CREATE INDEX IF NOT EXISTS monthly_ma_cluster_ticker_date_idx ON monthly_ma_cluster_daily(ticker, date)`,
  `CREATE TABLE IF NOT EXISTS monthly_ma_cluster_latest (
    ticker TEXT NOT NULL, cluster_key TEXT NOT NULL, date TEXT NOT NULL,
    periods_json TEXT NOT NULL, period_count INTEGER NOT NULL,
    cluster_type TEXT NOT NULL, is_strong INTEGER NOT NULL DEFAULT 0,
    band_low REAL NOT NULL, band_high REAL NOT NULL,
    band_average REAL NOT NULL, spread_pct REAL NOT NULL,
    close REAL NOT NULL, distance_pct REAL NOT NULL, abs_distance_pct REAL NOT NULL,
    approach_direction TEXT NOT NULL DEFAULT 'none',
    is_approaching INTEGER NOT NULL DEFAULT 0,
    approach_speed_pct_per_day REAL NOT NULL DEFAULT 0,
    is_touch INTEGER NOT NULL DEFAULT 0,
    last_touch_date TEXT, touch_age_sessions INTEGER,
    cross_direction TEXT, last_cross_date TEXT,
    last_cross_direction TEXT, cross_age_sessions INTEGER,
    primary_status TEXT NOT NULL, approach_score REAL NOT NULL,
    is_cluster INTEGER NOT NULL DEFAULT 0,
    is_maximal INTEGER NOT NULL DEFAULT 0,
    computed_at INTEGER NOT NULL DEFAULT (unixepoch()),
    PRIMARY KEY (ticker, cluster_key)
  )`,
  `CREATE INDEX IF NOT EXISTS monthly_ma_cluster_latest_date_state_idx ON monthly_ma_cluster_latest(date, is_cluster, is_maximal, approach_score)`,
  // ─── Phase 2: バッチ実行履歴 ───
  `CREATE TABLE IF NOT EXISTS batch_runs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    job_type TEXT NOT NULL,
    started_at INTEGER NOT NULL,
    finished_at INTEGER,
    status TEXT NOT NULL,
    total_tickers INTEGER,
    succeeded INTEGER DEFAULT 0,
    failed INTEGER DEFAULT 0,
    rows_inserted INTEGER DEFAULT 0,
    error_summary TEXT
  )`,
  // ─── Phase 3: 特徴量スナップショット (3 timescale × 30+ 次元) ───
  `CREATE TABLE IF NOT EXISTS feature_snapshots (
    ticker TEXT NOT NULL,
    date TEXT NOT NULL,
    timescale TEXT NOT NULL,
    bin_order_a_12 INTEGER, bin_order_a_13 INTEGER, bin_order_a_23 INTEGER,
    bin_order_b_12 INTEGER, bin_order_b_13 INTEGER, bin_order_b_23 INTEGER,
    rel_dist_a_12 REAL, rel_dist_a_13 REAL, rel_dist_a_23 REAL,
    rel_dist_b_12 REAL, rel_dist_b_13 REAL, rel_dist_b_23 REAL,
    divergence_a REAL, divergence_b REAL,
    divergence_a_delta REAL, divergence_b_delta REAL,
    fan_uniformity REAL, divergence_percentile REAL,
    stage_a_age INTEGER, stage_b_age INTEGER,
    slope_m1 REAL, accel_m1 REAL,
    slope_m2 REAL, accel_m2 REAL,
    slope_m3 REAL, accel_m3 REAL,
    slope_m4 REAL, accel_m4 REAL,
    slope_m5 REAL, accel_m5 REAL,
    angle_synchrony REAL,
    stage_a_oh TEXT, stage_b_oh TEXT,
    computed_at INTEGER NOT NULL DEFAULT (unixepoch()),
    PRIMARY KEY (ticker, date, timescale)
  )`,
  `CREATE INDEX IF NOT EXISTS feat_date_idx ON feature_snapshots(date)`,
  `CREATE INDEX IF NOT EXISTS feat_ts_idx ON feature_snapshots(timescale, date)`,
  // ─── Phase 3: フォワードリターン (4 horizon) ───
  `CREATE TABLE IF NOT EXISTS forward_returns (
    ticker TEXT NOT NULL,
    date TEXT NOT NULL,
    horizon_days INTEGER NOT NULL,
    return_pct REAL NOT NULL,
    return_category TEXT NOT NULL,
    end_date TEXT NOT NULL,
    PRIMARY KEY (ticker, date, horizon_days)
  )`,
  `CREATE INDEX IF NOT EXISTS fwd_date_idx ON forward_returns(date)`,
  `CREATE INDEX IF NOT EXISTS fwd_horizon_ticker_date_idx ON forward_returns(horizon_days, ticker, date)`,
  // ─── Phase 3: パターン統計 (6桁コード × horizon) ───
  `CREATE TABLE IF NOT EXISTS pattern_stats (
    pattern_code TEXT NOT NULL,
    horizon_days INTEGER NOT NULL,
    count INTEGER NOT NULL,
    p05 REAL, p25 REAL, p50 REAL, p75 REAL, p95 REAL,
    very_up_count INTEGER NOT NULL DEFAULT 0,
    up_count INTEGER NOT NULL DEFAULT 0,
    flat_count INTEGER NOT NULL DEFAULT 0,
    down_count INTEGER NOT NULL DEFAULT 0,
    very_down_count INTEGER NOT NULL DEFAULT 0,
    computed_at INTEGER NOT NULL DEFAULT (unixepoch()),
    PRIMARY KEY (pattern_code, horizon_days)
  )`,
  `CREATE INDEX IF NOT EXISTS pstat_code_idx ON pattern_stats(pattern_code)`,
  // ─── Phase 4: ステージ遷移カウント (6軸 × 6 from × 6 to = 216 行) ───
  `CREATE TABLE IF NOT EXISTS stage_transitions (
    axis TEXT NOT NULL,
    from_stage INTEGER NOT NULL,
    to_stage INTEGER NOT NULL,
    count INTEGER NOT NULL,
    computed_at INTEGER NOT NULL DEFAULT (unixepoch()),
    PRIMARY KEY (axis, from_stage, to_stage)
  )`,
  // ─── 業種・細分類の6ステージ構造集計 ───
  `CREATE TABLE IF NOT EXISTS sector_structure_daily (
    taxonomy TEXT NOT NULL,
    group_key TEXT NOT NULL,
    group_name TEXT NOT NULL,
    parent_group TEXT,
    date TEXT NOT NULL,
    n_stocks INTEGER NOT NULL,
    valid_stage_count INTEGER NOT NULL,
    strength_score REAL,
    transition_change_score REAL NOT NULL,
    momentum_5d REAL,
    momentum_10d REAL,
    momentum_20d REAL,
    propagation_direction TEXT NOT NULL DEFAULT 'neutral',
    propagation_phase INTEGER NOT NULL DEFAULT 0,
    propagation_label TEXT NOT NULL,
    improving_count INTEGER NOT NULL DEFAULT 0,
    deteriorating_count INTEGER NOT NULL DEFAULT 0,
    stable_count INTEGER NOT NULL DEFAULT 0,
    axis_json TEXT NOT NULL,
    composition_json TEXT NOT NULL,
    computed_at INTEGER NOT NULL DEFAULT (unixepoch()),
    PRIMARY KEY (taxonomy, group_key, date)
  )`,
  `CREATE INDEX IF NOT EXISTS sector_structure_taxonomy_date_idx
    ON sector_structure_daily(taxonomy, date)`,
  `CREATE INDEX IF NOT EXISTS sector_structure_date_momentum_idx
    ON sector_structure_daily(date, momentum_10d)`,
  // ─── Phase 4: 主要指数 OHLC (J-Quants /indices/bars/daily) ───
  `CREATE TABLE IF NOT EXISTS indices_daily (
    code TEXT NOT NULL,
    date TEXT NOT NULL,
    open REAL,
    high REAL,
    low REAL,
    close REAL,
    PRIMARY KEY (code, date)
  )`,
  `CREATE INDEX IF NOT EXISTS indices_date_idx ON indices_daily(date)`,
  // ─── Phase 4: 独自分類体系 (大分類 59 × 業種細分類 476) ───
  `CREATE TABLE IF NOT EXISTS stock_classification (
    ticker TEXT PRIMARY KEY,
    major_category TEXT NOT NULL,
    sub_industry TEXT NOT NULL,
    updated_at INTEGER NOT NULL DEFAULT (unixepoch())
  )`,
  `CREATE INDEX IF NOT EXISTS idx_classification_major ON stock_classification(major_category)`,
  `CREATE INDEX IF NOT EXISTS idx_classification_sub ON stock_classification(sub_industry)`,
  // ─── Phase 4: 信用残・空売り (J-Quants /markets/weekly_margin_interest) ───
  `CREATE TABLE IF NOT EXISTS weekly_margin_interest (
    ticker TEXT NOT NULL,
    date TEXT NOT NULL,
    long_margin REAL,
    short_margin REAL,
    long_change REAL,
    short_change REAL,
    imported_at INTEGER NOT NULL DEFAULT (unixepoch()),
    PRIMARY KEY (ticker, date)
  )`,
  `CREATE INDEX IF NOT EXISTS wmi_date_idx ON weekly_margin_interest(date)`,
  `CREATE INDEX IF NOT EXISTS wmi_ticker_date_idx ON weekly_margin_interest(ticker, date)`,
  `CREATE TABLE IF NOT EXISTS serving_margin_latest (
    ticker TEXT PRIMARY KEY,
    as_of_date TEXT NOT NULL,
    margin_type TEXT,
    long_margin REAL,
    short_margin REAL,
    long_change REAL,
    short_change REAL,
    credit_ratio REAL,
    short_ratio REAL,
    computed_at INTEGER NOT NULL DEFAULT (unixepoch())
  )`,
  `CREATE INDEX IF NOT EXISTS serving_margin_latest_date_idx ON serving_margin_latest(as_of_date)`,
  `CREATE INDEX IF NOT EXISTS serving_margin_latest_type_idx ON serving_margin_latest(margin_type, as_of_date)`,
  // ─── 企業概要: 財務サマリー / 日々公表信用残 ───
  `CREATE TABLE IF NOT EXISTS stock_financial_summaries (
    ticker TEXT NOT NULL,
    disclosure_no TEXT NOT NULL,
    disclosure_date TEXT NOT NULL,
    disclosure_time TEXT,
    document_type TEXT,
    period_type TEXT,
    period_start TEXT,
    period_end TEXT,
    fiscal_year_end TEXT,
    sales REAL,
    operating_profit REAL,
    ordinary_profit REAL,
    net_profit REAL,
    eps REAL,
    total_assets REAL,
    equity REAL,
    equity_ratio REAL,
    bps REAL,
    operating_cash_flow REAL,
    investing_cash_flow REAL,
    financing_cash_flow REAL,
    cash_equivalents REAL,
    annual_dividend REAL,
    payout_ratio REAL,
    forecast_sales REAL,
    forecast_operating_profit REAL,
    forecast_net_profit REAL,
    forecast_eps REAL,
    forecast_annual_dividend REAL,
    source TEXT NOT NULL DEFAULT 'jquants',
    imported_at INTEGER NOT NULL DEFAULT (unixepoch()),
    PRIMARY KEY (ticker, disclosure_no)
  )`,
  `CREATE INDEX IF NOT EXISTS stock_financial_date_idx
    ON stock_financial_summaries(ticker, disclosure_date DESC)`,
  `CREATE TABLE IF NOT EXISTS daily_margin_alerts (
    ticker TEXT NOT NULL,
    publication_date TEXT NOT NULL,
    application_date TEXT NOT NULL,
    publication_reason_json TEXT,
    short_outstanding REAL,
    short_change REAL,
    short_ratio REAL,
    long_outstanding REAL,
    long_change REAL,
    long_ratio REAL,
    short_long_ratio REAL,
    short_negotiable REAL,
    short_standardized REAL,
    long_negotiable REAL,
    long_standardized REAL,
    regulation_class TEXT,
    source TEXT NOT NULL DEFAULT 'jquants',
    imported_at INTEGER NOT NULL DEFAULT (unixepoch()),
    PRIMARY KEY (ticker, publication_date, application_date)
  )`,
  `CREATE INDEX IF NOT EXISTS daily_margin_alert_ticker_date_idx
    ON daily_margin_alerts(ticker, application_date DESC, publication_date DESC)`,
  `CREATE INDEX IF NOT EXISTS daily_margin_alert_date_idx
    ON daily_margin_alerts(application_date DESC)`,
  // ─── 企業概要: EDINET 有価証券報告書 / 大量保有報告書 ───
  `CREATE TABLE IF NOT EXISTS edinet_documents (
    document_id TEXT PRIMARY KEY,
    ticker TEXT,
    document_type TEXT NOT NULL,
    submitted_at TEXT,
    period_end TEXT,
    filer_name TEXT,
    status TEXT NOT NULL DEFAULT 'pending',
    error_message TEXT,
    processed_at INTEGER,
    imported_at INTEGER NOT NULL DEFAULT (unixepoch())
  )`,
  `CREATE INDEX IF NOT EXISTS edinet_documents_ticker_type_idx
    ON edinet_documents(ticker, document_type, submitted_at DESC)`,
  `CREATE TABLE IF NOT EXISTS major_shareholders (
    ticker TEXT NOT NULL,
    document_id TEXT NOT NULL,
    rank INTEGER NOT NULL,
    fiscal_year_end TEXT,
    holder_name TEXT NOT NULL,
    shares REAL,
    holding_ratio REAL,
    submitted_at TEXT,
    source TEXT NOT NULL DEFAULT 'edinet',
    imported_at INTEGER NOT NULL DEFAULT (unixepoch()),
    PRIMARY KEY (ticker, document_id, rank)
  )`,
  `CREATE INDEX IF NOT EXISTS major_shareholders_ticker_date_idx
    ON major_shareholders(ticker, fiscal_year_end DESC, rank)`,
  `CREATE TABLE IF NOT EXISTS policy_holdings (
    ticker TEXT NOT NULL,
    document_id TEXT NOT NULL,
    rank INTEGER NOT NULL,
    fiscal_year_end TEXT,
    issuer_name TEXT NOT NULL,
    shares REAL,
    book_value REAL,
    purpose TEXT,
    quantitative_effect TEXT,
    holding_type TEXT,
    submitted_at TEXT,
    source TEXT NOT NULL DEFAULT 'edinet',
    imported_at INTEGER NOT NULL DEFAULT (unixepoch()),
    PRIMARY KEY (ticker, document_id, rank)
  )`,
  `CREATE INDEX IF NOT EXISTS policy_holdings_ticker_date_idx
    ON policy_holdings(ticker, fiscal_year_end DESC, book_value DESC)`,
  `CREATE TABLE IF NOT EXISTS large_holding_reports (
    ticker TEXT NOT NULL,
    document_id TEXT NOT NULL,
    submitted_at TEXT,
    report_date TEXT,
    holder_name TEXT,
    shares REAL,
    holding_ratio REAL,
    previous_holding_ratio REAL,
    purpose TEXT,
    report_kind TEXT,
    source TEXT NOT NULL DEFAULT 'edinet',
    imported_at INTEGER NOT NULL DEFAULT (unixepoch()),
    PRIMARY KEY (ticker, document_id)
  )`,
  `CREATE INDEX IF NOT EXISTS large_holding_reports_ticker_date_idx
    ON large_holding_reports(ticker, submitted_at DESC)`,
  `CREATE TABLE IF NOT EXISTS stock_external_data_status (
    ticker TEXT NOT NULL,
    dataset TEXT NOT NULL,
    status TEXT NOT NULL,
    source_date TEXT,
    message TEXT,
    attempted_at INTEGER NOT NULL DEFAULT (unixepoch()),
    PRIMARY KEY (ticker, dataset)
  )`,
  // ─── Phase 4: 空売り残高 ───
  `CREATE TABLE IF NOT EXISTS short_selling_positions (
    ticker TEXT NOT NULL,
    date TEXT NOT NULL,
    short_ratio REAL,
    reporter TEXT NOT NULL DEFAULT '',
    imported_at INTEGER NOT NULL DEFAULT (unixepoch()),
    PRIMARY KEY (ticker, date, reporter)
  )`,
  `CREATE INDEX IF NOT EXISTS ssp_date_idx ON short_selling_positions(date)`,
  `CREATE INDEX IF NOT EXISTS ssp_ticker_date_idx ON short_selling_positions(ticker, date)`,
  // ─── Phase 4: 決算発表カレンダー ───
  `CREATE TABLE IF NOT EXISTS earnings_calendar (
    ticker TEXT NOT NULL,
    announce_date TEXT NOT NULL,
    fiscal_period TEXT,
    company_name TEXT,
    sector_name TEXT,
    market_segment TEXT,
    source TEXT,
    source_url TEXT,
    scheduled_time TEXT,
    scheduled_time_kind TEXT,
    scheduled_time_source TEXT,
    scheduled_time_source_url TEXT,
    predicted_time TEXT,
    prediction_confidence TEXT,
    prediction_sample_count INTEGER,
    prediction_mode_count INTEGER,
    actual_disclosed_date TEXT,
    actual_disclosed_time TEXT,
    actual_disclosed_at TEXT,
    actual_source TEXT,
    actual_source_url TEXT,
    time_bucket TEXT,
    time_updated_at INTEGER,
    imported_at INTEGER NOT NULL DEFAULT (unixepoch()),
    PRIMARY KEY (ticker, announce_date)
  )`,
  `CREATE INDEX IF NOT EXISTS earn_date_idx ON earnings_calendar(announce_date)`,
  `CREATE INDEX IF NOT EXISTS earn_import_date_ticker_idx
    ON earnings_calendar(imported_at, announce_date, ticker)`,
  // ─── Phase 4: 6 桁パターンコード検索用 expression index ───
  `CREATE INDEX IF NOT EXISTS idx_ds_pattern_code ON daily_snapshots(
    (CAST(daily_a_stage AS TEXT) || CAST(daily_b_stage AS TEXT) || CAST(weekly_a_stage AS TEXT) || CAST(weekly_b_stage AS TEXT) || CAST(monthly_a_stage AS TEXT) || CAST(monthly_b_stage AS TEXT))
  )`,
  // ─── Phase 5: Backtest / ML-RL readiness ───
  `CREATE TABLE IF NOT EXISTS weekly_ohlcv (
    ticker TEXT NOT NULL,
    date TEXT NOT NULL,
    week_start_date TEXT NOT NULL,
    week_end_date TEXT NOT NULL,
    open REAL NOT NULL,
    high REAL NOT NULL,
    low REAL NOT NULL,
    close REAL NOT NULL,
    volume INTEGER NOT NULL,
    ma_5 REAL,
    ma_13 REAL,
    ma_25 REAL,
    ma_50 REAL,
    ma_100 REAL,
    computed_at INTEGER NOT NULL DEFAULT (unixepoch()),
    PRIMARY KEY (ticker, date)
  )`,
  `CREATE INDEX IF NOT EXISTS weekly_ohlcv_date_idx ON weekly_ohlcv(date)`,
  `CREATE TABLE IF NOT EXISTS technical_signals (
    ticker TEXT NOT NULL,
    date TEXT NOT NULL,
    timescale TEXT NOT NULL,
    ma_period INTEGER NOT NULL DEFAULT 0,
    signal_code TEXT NOT NULL,
    signal_strength TEXT NOT NULL,
    direction TEXT NOT NULL,
    label TEXT NOT NULL,
    score_component REAL,
    value_json TEXT,
    computed_at INTEGER NOT NULL DEFAULT (unixepoch()),
    PRIMARY KEY (ticker, date, timescale, ma_period, signal_code)
  )`,
  `CREATE INDEX IF NOT EXISTS tech_signal_date_idx ON technical_signals(date, signal_code)`,
  `CREATE INDEX IF NOT EXISTS tech_signal_code_idx ON technical_signals(signal_code, date)`,
  `CREATE INDEX IF NOT EXISTS tech_signal_date_ticker_idx ON technical_signals(date, ticker)`,
  `CREATE INDEX IF NOT EXISTS tech_signal_ticker_code_date_idx ON technical_signals(ticker, signal_code, date)`,
  `CREATE TABLE IF NOT EXISTS forward_extrema (
    ticker TEXT NOT NULL,
    date TEXT NOT NULL,
    horizon_days INTEGER NOT NULL,
    return_pct REAL,
    end_date TEXT,
    max_return_pct REAL,
    max_return_date TEXT,
    days_to_max INTEGER,
    min_return_pct REAL,
    min_return_date TEXT,
    days_to_min INTEGER,
    hit_10 INTEGER NOT NULL DEFAULT 0,
    hit_20 INTEGER NOT NULL DEFAULT 0,
    hit_40 INTEGER NOT NULL DEFAULT 0,
    days_to_10 INTEGER,
    days_to_20 INTEGER,
    days_to_40 INTEGER,
    computed_at INTEGER NOT NULL DEFAULT (unixepoch()),
    PRIMARY KEY (ticker, date, horizon_days)
  )`,
  `CREATE INDEX IF NOT EXISTS fext_date_horizon_idx ON forward_extrema(date, horizon_days)`,
  `CREATE INDEX IF NOT EXISTS fext_date_horizon_ticker_idx ON forward_extrema(date, horizon_days, ticker)`,
  `CREATE INDEX IF NOT EXISTS fext_date_horizon_max_return_idx ON forward_extrema(date, horizon_days, max_return_pct DESC)`,
  `CREATE INDEX IF NOT EXISTS fext_horizon_date_idx ON forward_extrema(horizon_days, date)`,
  `CREATE INDEX IF NOT EXISTS fext_horizon_max_idx ON forward_extrema(horizon_days, max_return_pct)`,
  `CREATE TABLE IF NOT EXISTS forward_extrema_date_coverage (
    horizon_days INTEGER NOT NULL,
    date TEXT NOT NULL,
    updated_at INTEGER NOT NULL DEFAULT (unixepoch()),
    PRIMARY KEY (horizon_days, date)
  )`,
  `CREATE TABLE IF NOT EXISTS model_features (
    ticker TEXT NOT NULL,
    date TEXT NOT NULL,
    pattern_code TEXT,
    daily_a_stage INTEGER,
    daily_b_stage INTEGER,
    weekly_a_stage INTEGER,
    weekly_b_stage INTEGER,
    monthly_a_stage INTEGER,
    monthly_b_stage INTEGER,
    close REAL,
    volume INTEGER,
    volume_ratio_20 REAL,
    range_pct REAL,
    atr20_pct REAL,
    ma5_pos_pct REAL,
    ma25_pos_pct REAL,
    ma75_pos_pct REAL,
    ma_spread_pct REAL,
    rel_strength_20 REAL,
    signal_codes TEXT,
    feature_json TEXT,
    computed_at INTEGER NOT NULL DEFAULT (unixepoch()),
    PRIMARY KEY (ticker, date)
  )`,
  `CREATE INDEX IF NOT EXISTS model_features_date_idx ON model_features(date)`,
  `CREATE INDEX IF NOT EXISTS model_features_pattern_idx ON model_features(pattern_code, date)`,
  `CREATE INDEX IF NOT EXISTS model_features_ticker_date_idx ON model_features(ticker, date)`,
  `CREATE TABLE IF NOT EXISTS model_labels (
    ticker TEXT NOT NULL,
    date TEXT NOT NULL,
    horizon_days INTEGER NOT NULL,
    return_pct REAL,
    max_return_pct REAL,
    min_return_pct REAL,
    days_to_max INTEGER,
    hit_10 INTEGER NOT NULL DEFAULT 0,
    hit_20 INTEGER NOT NULL DEFAULT 0,
    hit_40 INTEGER NOT NULL DEFAULT 0,
    reward_score REAL,
    label_json TEXT,
    computed_at INTEGER NOT NULL DEFAULT (unixepoch()),
    PRIMARY KEY (ticker, date, horizon_days)
  )`,
  `CREATE INDEX IF NOT EXISTS model_labels_date_idx ON model_labels(date, horizon_days)`,
  `CREATE TABLE IF NOT EXISTS signal_stats (
    signal_code TEXT NOT NULL,
    pattern_code TEXT NOT NULL,
    horizon_days INTEGER NOT NULL,
    count INTEGER NOT NULL,
    hit_10_rate REAL,
    hit_20_rate REAL,
    hit_40_rate REAL,
    max_return_p25 REAL,
    max_return_p50 REAL,
    max_return_p75 REAL,
    return_p50 REAL,
    min_return_p50 REAL,
    days_to_max_p50 REAL,
    computed_at INTEGER NOT NULL DEFAULT (unixepoch()),
    PRIMARY KEY (signal_code, pattern_code, horizon_days)
  )`,
  `CREATE INDEX IF NOT EXISTS signal_stats_code_idx ON signal_stats(signal_code, horizon_days, count)`,
  `CREATE TABLE IF NOT EXISTS signal_return_stats (
    signal_code TEXT NOT NULL,
    horizon_days INTEGER NOT NULL,
    count INTEGER NOT NULL,
    up_rate REAL,
    down_rate REAL,
    median_return_pct REAL,
    avg_return_pct REAL,
    computed_at INTEGER NOT NULL DEFAULT (unixepoch()),
    PRIMARY KEY (signal_code, horizon_days)
  )`,
  `CREATE INDEX IF NOT EXISTS signal_return_stats_code_idx ON signal_return_stats(signal_code, horizon_days, count)`,
  `CREATE TABLE IF NOT EXISTS serving_latest_signals (
    date TEXT NOT NULL,
    ticker TEXT NOT NULL,
    rank INTEGER NOT NULL,
    score REAL NOT NULL,
    signal_codes TEXT NOT NULL,
    summary_json TEXT NOT NULL,
    computed_at INTEGER NOT NULL DEFAULT (unixepoch()),
    PRIMARY KEY (date, ticker)
  )`,
  `CREATE INDEX IF NOT EXISTS serving_latest_rank_idx ON serving_latest_signals(date, rank)`,
  `CREATE TABLE IF NOT EXISTS serving_signal_stats (
    signal_code TEXT NOT NULL,
    pattern_code TEXT NOT NULL,
    horizon_days INTEGER NOT NULL,
    payload_json TEXT NOT NULL,
    computed_at INTEGER NOT NULL DEFAULT (unixepoch()),
    PRIMARY KEY (signal_code, pattern_code, horizon_days)
  )`,
  `CREATE TABLE IF NOT EXISTS serving_backtest_dates (
    date TEXT PRIMARY KEY,
    total_tickers INTEGER NOT NULL,
    signal_tickers INTEGER NOT NULL,
    computed_at INTEGER NOT NULL DEFAULT (unixepoch())
  )`,
  `CREATE TABLE IF NOT EXISTS serving_backtest_summaries (
    date TEXT NOT NULL,
    horizon_days INTEGER NOT NULL,
    condition_key TEXT NOT NULL,
    payload_json TEXT NOT NULL,
    computed_at INTEGER NOT NULL DEFAULT (unixepoch()),
    PRIMARY KEY (date, horizon_days, condition_key)
  )`,
  `CREATE INDEX IF NOT EXISTS serving_summary_date_idx ON serving_backtest_summaries(date, horizon_days)`,
  `CREATE TABLE IF NOT EXISTS serving_similar_cases (
    source_ticker TEXT NOT NULL,
    source_date TEXT NOT NULL,
    rank INTEGER NOT NULL,
    similar_ticker TEXT NOT NULL,
    similar_date TEXT NOT NULL,
    similarity_score REAL NOT NULL,
    payload_json TEXT NOT NULL,
    computed_at INTEGER NOT NULL DEFAULT (unixepoch()),
    PRIMARY KEY (source_ticker, source_date, rank)
  )`,
  `CREATE TABLE IF NOT EXISTS serving_backtest_results (
    date TEXT NOT NULL,
    horizon_days INTEGER NOT NULL,
    ticker TEXT NOT NULL,
    name TEXT,
    sector_large TEXT,
    sector_small TEXT,
    market_segment TEXT,
    pattern_code TEXT,
    daily_a_stage INTEGER,
    daily_b_stage INTEGER,
    weekly_a_stage INTEGER,
    weekly_b_stage INTEGER,
    monthly_a_stage INTEGER,
    monthly_b_stage INTEGER,
    open REAL,
    high REAL,
    low REAL,
    close REAL,
    volume INTEGER,
    volume_ratio_20 REAL,
    range_pct REAL,
    atr20_pct REAL,
    ma5_pos_pct REAL,
    ma25_pos_pct REAL,
    ma75_pos_pct REAL,
    signal_codes TEXT,
    return_pct REAL,
    max_return_pct REAL,
    max_return_date TEXT,
    days_to_max INTEGER,
    min_return_pct REAL,
    min_return_date TEXT,
    days_to_min INTEGER,
    hit_10 INTEGER,
    hit_20 INTEGER,
    hit_40 INTEGER,
    computed_at INTEGER NOT NULL DEFAULT (unixepoch()),
    PRIMARY KEY (date, horizon_days, ticker)
  )`,
  `CREATE INDEX IF NOT EXISTS serving_backtest_results_sort_idx ON serving_backtest_results(date, horizon_days, max_return_pct)`,
  `CREATE INDEX IF NOT EXISTS serving_backtest_results_horizon_date_idx ON serving_backtest_results(horizon_days, date DESC)`,
  `CREATE INDEX IF NOT EXISTS serving_backtest_results_ticker_idx ON serving_backtest_results(ticker, date)`,
  `CREATE TABLE IF NOT EXISTS serving_backtest_details (
    date TEXT NOT NULL,
    horizon_days INTEGER NOT NULL,
    ticker TEXT NOT NULL,
    detail_json TEXT NOT NULL,
    computed_at INTEGER NOT NULL DEFAULT (unixepoch()),
    PRIMARY KEY (date, horizon_days, ticker)
  )`,
  `CREATE TABLE IF NOT EXISTS serving_signal_evidence (
    ticker TEXT NOT NULL,
    date TEXT NOT NULL,
    signal_code TEXT NOT NULL,
    label TEXT,
    reason_json TEXT NOT NULL,
    computed_at INTEGER NOT NULL DEFAULT (unixepoch()),
    PRIMARY KEY (ticker, date, signal_code)
  )`,
  `CREATE INDEX IF NOT EXISTS serving_signal_evidence_date_idx ON serving_signal_evidence(date, signal_code)`,
  `CREATE TABLE IF NOT EXISTS serving_stock_metrics (
    ticker TEXT PRIMARY KEY,
    as_of_date TEXT NOT NULL,
    payload_json TEXT NOT NULL,
    computed_at INTEGER NOT NULL DEFAULT (unixepoch())
  )`,
  `CREATE TABLE IF NOT EXISTS serving_stock_move_periods (
    ticker TEXT NOT NULL,
    direction TEXT NOT NULL,
    rank INTEGER NOT NULL,
    start_date TEXT NOT NULL,
    end_date TEXT NOT NULL,
    return_pct REAL NOT NULL,
    trading_days INTEGER NOT NULL,
    stage_path_json TEXT NOT NULL,
    payload_json TEXT NOT NULL,
    computed_at INTEGER NOT NULL DEFAULT (unixepoch()),
    PRIMARY KEY (ticker, direction, rank)
  )`,
  `CREATE INDEX IF NOT EXISTS serving_stock_move_ticker_idx ON serving_stock_move_periods(ticker, direction, rank)`,
  `CREATE TABLE IF NOT EXISTS ml_feature_vectors (
    ticker TEXT NOT NULL,
    date TEXT NOT NULL,
    stage_code TEXT,
    feature_json TEXT NOT NULL,
    vector_json TEXT NOT NULL,
    computed_at INTEGER NOT NULL DEFAULT (unixepoch()),
    PRIMARY KEY (ticker, date)
  )`,
  `CREATE INDEX IF NOT EXISTS ml_feature_vectors_date_idx ON ml_feature_vectors(date)`,
  `CREATE TABLE IF NOT EXISTS ml_feature_vectors_v2 (
    ticker TEXT NOT NULL,
    date TEXT NOT NULL,
    feature_set TEXT NOT NULL,
    version INTEGER NOT NULL DEFAULT 1,
    stage_code TEXT,
    feature_json TEXT NOT NULL,
    vector_json TEXT NOT NULL,
    computed_at INTEGER NOT NULL DEFAULT (unixepoch()),
    PRIMARY KEY (ticker, date, feature_set)
  )`,
  `CREATE INDEX IF NOT EXISTS ml_feature_vectors_v2_date_idx ON ml_feature_vectors_v2(feature_set, date)`,
  `CREATE INDEX IF NOT EXISTS ml_feature_vectors_v2_date_only_idx ON ml_feature_vectors_v2(date)`,
  `CREATE INDEX IF NOT EXISTS ml_feature_vectors_v2_ticker_date_idx ON ml_feature_vectors_v2(ticker, date)`,
  `CREATE INDEX IF NOT EXISTS ml_feature_vectors_v2_feature_ticker_date_idx ON ml_feature_vectors_v2(feature_set, ticker, date)`,
  `CREATE TABLE IF NOT EXISTS ml_training_labels (
    ticker TEXT NOT NULL,
    date TEXT NOT NULL,
    horizon_days INTEGER NOT NULL,
    return_pct REAL,
    max_return_pct REAL,
    min_return_pct REAL,
    up_label INTEGER NOT NULL DEFAULT 0,
    down_label INTEGER NOT NULL DEFAULT 0,
    reward_score REAL,
    label_json TEXT,
    computed_at INTEGER NOT NULL DEFAULT (unixepoch()),
    PRIMARY KEY (ticker, date, horizon_days)
  )`,
  `CREATE INDEX IF NOT EXISTS ml_training_labels_date_idx ON ml_training_labels(date, horizon_days)`,
  `CREATE TABLE IF NOT EXISTS ml_short_labels (
    ticker TEXT NOT NULL,
    date TEXT NOT NULL,
    horizon_days INTEGER NOT NULL,
    return_pct REAL,
    max_return_pct REAL,
    min_return_pct REAL,
    up_label INTEGER NOT NULL DEFAULT 0,
    down_label INTEGER NOT NULL DEFAULT 0,
    wait_label INTEGER NOT NULL DEFAULT 0,
    reward_long REAL,
    reward_short REAL,
    reward_wait REAL,
    label_json TEXT NOT NULL,
    computed_at INTEGER NOT NULL DEFAULT (unixepoch()),
    PRIMARY KEY (ticker, date, horizon_days)
  )`,
  `CREATE INDEX IF NOT EXISTS ml_short_labels_date_idx ON ml_short_labels(date, horizon_days)`,
  `CREATE INDEX IF NOT EXISTS ml_short_labels_horizon_idx ON ml_short_labels(horizon_days, date)`,
  `CREATE TABLE IF NOT EXISTS ml_models (
    model_name TEXT PRIMARY KEY,
    model_type TEXT NOT NULL,
    direction TEXT NOT NULL,
    horizon_days INTEGER NOT NULL,
    feature_names_json TEXT NOT NULL,
    weights_json TEXT NOT NULL,
    intercept REAL NOT NULL DEFAULT 0,
    metrics_json TEXT NOT NULL,
    trained_at INTEGER NOT NULL DEFAULT (unixepoch())
  )`,
  `CREATE INDEX IF NOT EXISTS ml_models_latest_idx ON ml_models(horizon_days, direction, trained_at)`,
  `CREATE TABLE IF NOT EXISTS ml_prediction_runs (
    run_id TEXT PRIMARY KEY,
    as_of_date TEXT NOT NULL,
    horizon_days INTEGER NOT NULL,
    direction TEXT NOT NULL,
    model_name TEXT,
    model_type TEXT NOT NULL,
    prediction_count INTEGER NOT NULL DEFAULT 0,
    source TEXT NOT NULL DEFAULT 'batch',
    status TEXT NOT NULL DEFAULT 'success',
    created_at INTEGER NOT NULL DEFAULT (unixepoch())
  )`,
  `CREATE INDEX IF NOT EXISTS ml_prediction_runs_date_idx ON ml_prediction_runs(as_of_date, horizon_days, direction)`,
  `CREATE TABLE IF NOT EXISTS ml_predictions (
    as_of_date TEXT NOT NULL,
    horizon_days INTEGER NOT NULL,
    direction TEXT NOT NULL,
    ticker TEXT NOT NULL,
    run_id TEXT NOT NULL,
    rank INTEGER NOT NULL,
    score REAL NOT NULL,
    model_name TEXT,
    feature_json TEXT NOT NULL,
    reason_json TEXT NOT NULL,
    explanation_json TEXT NOT NULL,
    created_at INTEGER NOT NULL DEFAULT (unixepoch()),
    PRIMARY KEY (as_of_date, horizon_days, direction, ticker)
  )`,
  `CREATE INDEX IF NOT EXISTS ml_predictions_rank_idx ON ml_predictions(as_of_date, horizon_days, direction, rank)`,
  `CREATE INDEX IF NOT EXISTS ml_predictions_ticker_idx ON ml_predictions(ticker, as_of_date)`,
  `CREATE TABLE IF NOT EXISTS ml_prediction_outcomes (
    as_of_date TEXT NOT NULL,
    horizon_days INTEGER NOT NULL,
    direction TEXT NOT NULL,
    ticker TEXT NOT NULL,
    score REAL NOT NULL,
    rank INTEGER NOT NULL,
    return_pct REAL,
    max_return_pct REAL,
    min_return_pct REAL,
    hit_label INTEGER NOT NULL DEFAULT 0,
    miss_label INTEGER NOT NULL DEFAULT 0,
    outcome_json TEXT NOT NULL,
    evaluated_at INTEGER NOT NULL DEFAULT (unixepoch()),
    PRIMARY KEY (as_of_date, horizon_days, direction, ticker)
  )`,
  `CREATE INDEX IF NOT EXISTS ml_prediction_outcomes_date_idx ON ml_prediction_outcomes(as_of_date, horizon_days, direction)`,
  `CREATE INDEX IF NOT EXISTS ml_prediction_outcomes_ticker_idx ON ml_prediction_outcomes(ticker, as_of_date)`,
  `CREATE TABLE IF NOT EXISTS ml_model_evaluations (
    evaluation_id TEXT PRIMARY KEY,
    model_name TEXT,
    model_type TEXT NOT NULL,
    direction TEXT NOT NULL,
    horizon_days INTEGER NOT NULL,
    evaluation_date TEXT NOT NULL,
    train_start_date TEXT,
    train_end_date TEXT,
    validation_start_date TEXT,
    validation_end_date TEXT,
    sample_count INTEGER NOT NULL DEFAULT 0,
    precision_at_20 REAL,
    precision_at_50 REAL,
    precision_at_80 REAL,
    hit_rate REAL,
    median_return_pct REAL,
    avg_return_pct REAL,
    max_drawdown_pct REAL,
    metrics_json TEXT NOT NULL,
    created_at INTEGER NOT NULL DEFAULT (unixepoch())
  )`,
  `CREATE INDEX IF NOT EXISTS ml_model_evaluations_latest_idx ON ml_model_evaluations(evaluation_date, direction, horizon_days)`,
  `CREATE TABLE IF NOT EXISTS rl_training_states (
    ticker TEXT NOT NULL,
    date TEXT NOT NULL,
    horizon_days INTEGER NOT NULL,
    action TEXT NOT NULL,
    state_json TEXT NOT NULL,
    reward REAL,
    next_state_json TEXT,
    computed_at INTEGER NOT NULL DEFAULT (unixepoch()),
    PRIMARY KEY (ticker, date, horizon_days, action)
  )`,
  `CREATE INDEX IF NOT EXISTS rl_training_states_date_idx ON rl_training_states(date, horizon_days)`,
  `CREATE TABLE IF NOT EXISTS rl_training_states_v2 (
    ticker TEXT NOT NULL,
    date TEXT NOT NULL,
    horizon_days INTEGER NOT NULL,
    action TEXT NOT NULL,
    state_json TEXT NOT NULL,
    reward REAL,
    next_state_json TEXT,
    computed_at INTEGER NOT NULL DEFAULT (unixepoch()),
    PRIMARY KEY (ticker, date, horizon_days, action)
  )`,
  `CREATE INDEX IF NOT EXISTS rl_training_states_v2_date_idx ON rl_training_states_v2(date, horizon_days)`,
  `CREATE TABLE IF NOT EXISTS ml_rl_policy_evaluations (
    evaluation_id TEXT PRIMARY KEY,
    policy_name TEXT NOT NULL,
    policy_type TEXT NOT NULL,
    horizon_days INTEGER NOT NULL,
    evaluation_date TEXT NOT NULL,
    start_date TEXT,
    end_date TEXT,
    sample_count INTEGER NOT NULL DEFAULT 0,
    long_count INTEGER NOT NULL DEFAULT 0,
    short_count INTEGER NOT NULL DEFAULT 0,
    wait_count INTEGER NOT NULL DEFAULT 0,
    win_rate REAL,
    oracle_match_rate REAL,
    avg_reward REAL,
    median_reward REAL,
    avg_return_pct REAL,
    max_drawdown_pct REAL,
    action_breakdown_json TEXT NOT NULL,
    metrics_json TEXT NOT NULL,
    created_at INTEGER NOT NULL DEFAULT (unixepoch())
  )`,
  `CREATE INDEX IF NOT EXISTS ml_rl_policy_evaluations_latest_idx ON ml_rl_policy_evaluations(evaluation_date, horizon_days, policy_name)`,
  `CREATE TABLE IF NOT EXISTS ml_physics_status_evaluations (
    evaluation_id TEXT PRIMARY KEY,
    evaluation_date TEXT NOT NULL,
    feature_set TEXT NOT NULL,
    status_label TEXT NOT NULL,
    target_direction TEXT NOT NULL,
    horizon_days INTEGER NOT NULL,
    start_date TEXT,
    end_date TEXT,
    sample_count INTEGER NOT NULL DEFAULT 0,
    hit_count INTEGER NOT NULL DEFAULT 0,
    adverse_count INTEGER NOT NULL DEFAULT 0,
    hit_rate REAL,
    base_rate REAL,
    lift REAL,
    confidence_score REAL,
    median_return_pct REAL,
    avg_return_pct REAL,
    avg_max_return_pct REAL,
    avg_min_return_pct REAL,
    adverse_rate REAL,
    metrics_json TEXT NOT NULL,
    created_at INTEGER NOT NULL DEFAULT (unixepoch())
  )`,
  `CREATE INDEX IF NOT EXISTS ml_physics_status_evaluations_latest_idx ON ml_physics_status_evaluations(evaluation_date, horizon_days, status_label)`,
  `CREATE INDEX IF NOT EXISTS ml_physics_status_evaluations_status_idx ON ml_physics_status_evaluations(status_label, horizon_days, evaluation_date)`,
  `CREATE INDEX IF NOT EXISTS ml_physics_status_evaluations_lookup_idx
     ON ml_physics_status_evaluations(feature_set, status_label, horizon_days, evaluation_date)`,
  `CREATE TABLE IF NOT EXISTS serving_ml_candidates (
    as_of_date TEXT NOT NULL,
    direction TEXT NOT NULL,
    rank INTEGER NOT NULL,
    ticker TEXT NOT NULL,
    name TEXT,
    sector_large TEXT,
    candidate_score REAL NOT NULL,
    model_name TEXT,
    feature_json TEXT NOT NULL,
    reason_json TEXT NOT NULL,
    explanation_json TEXT NOT NULL,
    computed_at INTEGER NOT NULL DEFAULT (unixepoch()),
    PRIMARY KEY (as_of_date, direction, ticker)
  )`,
  `CREATE INDEX IF NOT EXISTS serving_ml_candidates_rank_idx ON serving_ml_candidates(as_of_date, direction, rank)`,
  `CREATE TABLE IF NOT EXISTS serving_ml_physics_candidates (
    as_of_date TEXT NOT NULL,
    direction TEXT NOT NULL,
    horizon_days INTEGER NOT NULL,
    rank INTEGER NOT NULL,
    ticker TEXT NOT NULL,
    name TEXT,
    sector_large TEXT,
    candidate_score REAL NOT NULL,
    model_name TEXT,
    feature_json TEXT NOT NULL,
    reason_json TEXT NOT NULL,
    explanation_json TEXT NOT NULL,
    computed_at INTEGER NOT NULL DEFAULT (unixepoch()),
    PRIMARY KEY (as_of_date, direction, horizon_days, ticker)
  )`,
  `CREATE INDEX IF NOT EXISTS serving_ml_physics_candidates_rank_idx ON serving_ml_physics_candidates(as_of_date, horizon_days, direction, rank)`,
  `CREATE INDEX IF NOT EXISTS serving_ml_physics_candidates_ticker_idx ON serving_ml_physics_candidates(ticker, as_of_date)`,
  `CREATE INDEX IF NOT EXISTS serving_ml_physics_candidates_horizon_date_idx
     ON serving_ml_physics_candidates(horizon_days, as_of_date)`,
  `CREATE INDEX IF NOT EXISTS serving_ml_physics_candidates_horizon_ticker_date_idx
     ON serving_ml_physics_candidates(horizon_days, ticker, as_of_date)`,
  `CREATE TABLE IF NOT EXISTS serving_current_similars (
    as_of_date TEXT NOT NULL,
    base_ticker TEXT NOT NULL,
    rank INTEGER NOT NULL,
    similar_ticker TEXT NOT NULL,
    similarity_score REAL NOT NULL,
    base_direction TEXT,
    similar_direction TEXT,
    payload_json TEXT NOT NULL,
    reason_json TEXT NOT NULL,
    computed_at INTEGER NOT NULL DEFAULT (unixepoch()),
    PRIMARY KEY (as_of_date, base_ticker, rank)
  )`,
  `CREATE INDEX IF NOT EXISTS serving_current_similars_base_idx ON serving_current_similars(as_of_date, base_ticker)`,
  `CREATE INDEX IF NOT EXISTS serving_current_similars_score_idx ON serving_current_similars(as_of_date, similarity_score)`,
  `CREATE INDEX IF NOT EXISTS serving_current_similars_similar_idx ON serving_current_similars(as_of_date, similar_ticker)`,
  `CREATE TABLE IF NOT EXISTS serving_ml_sector_rankings (
    as_of_date TEXT NOT NULL,
    sector_type TEXT NOT NULL,
    sector_name TEXT NOT NULL,
    direction TEXT NOT NULL,
    candidate_count INTEGER NOT NULL DEFAULT 0,
    avg_score REAL,
    representative_tickers_json TEXT NOT NULL,
    computed_at INTEGER NOT NULL DEFAULT (unixepoch()),
    PRIMARY KEY (as_of_date, sector_type, sector_name, direction)
  )`,
  `CREATE INDEX IF NOT EXISTS serving_ml_sector_rankings_rank_idx ON serving_ml_sector_rankings(as_of_date, sector_type, direction, candidate_count)`,
  `CREATE TABLE IF NOT EXISTS serving_ml_performance (
    as_of_date TEXT NOT NULL,
    direction TEXT NOT NULL,
    horizon_days INTEGER NOT NULL,
    sector_type TEXT NOT NULL DEFAULT 'all',
    sector_name TEXT NOT NULL DEFAULT 'ALL',
    sample_count INTEGER NOT NULL DEFAULT 0,
    up_rate REAL,
    down_rate REAL,
    median_return_pct REAL,
    avg_return_pct REAL,
    payload_json TEXT NOT NULL,
    computed_at INTEGER NOT NULL DEFAULT (unixepoch()),
    PRIMARY KEY (as_of_date, direction, horizon_days, sector_type, sector_name)
  )`,
  `CREATE INDEX IF NOT EXISTS serving_ml_performance_rank_idx ON serving_ml_performance(as_of_date, direction, horizon_days, sample_count)`,
  `CREATE TABLE IF NOT EXISTS ml_market_context_features (
    date TEXT PRIMARY KEY,
    market_return_5 REAL,
    market_return_20 REAL,
    market_above_sma25_rate REAL,
    market_above_sma75_rate REAL,
    advancers_rate_5 REAL,
    sample_count INTEGER NOT NULL DEFAULT 0,
    payload_json TEXT NOT NULL,
    computed_at INTEGER NOT NULL DEFAULT (unixepoch())
  )`,
  `CREATE TABLE IF NOT EXISTS ml_sector_context_features (
    date TEXT NOT NULL,
    sector_type TEXT NOT NULL,
    sector_name TEXT NOT NULL,
    return_5 REAL,
    return_20 REAL,
    above_sma25_rate REAL,
    rank_pct REAL,
    sample_count INTEGER NOT NULL DEFAULT 0,
    payload_json TEXT NOT NULL,
    computed_at INTEGER NOT NULL DEFAULT (unixepoch()),
    PRIMARY KEY (date, sector_type, sector_name)
  )`,
  `CREATE INDEX IF NOT EXISTS ml_sector_context_features_rank_idx ON ml_sector_context_features(date, sector_type, rank_pct)`,
  `CREATE TABLE IF NOT EXISTS ml_similarity_evaluations (
    as_of_date TEXT NOT NULL,
    horizon_days INTEGER NOT NULL,
    source TEXT NOT NULL,
    base_count INTEGER NOT NULL DEFAULT 0,
    pair_count INTEGER NOT NULL DEFAULT 0,
    up_rate REAL,
    down_rate REAL,
    median_return_pct REAL,
    avg_return_pct REAL,
    max_drawdown_pct REAL,
    payload_json TEXT NOT NULL,
    computed_at INTEGER NOT NULL DEFAULT (unixepoch()),
    PRIMARY KEY (as_of_date, horizon_days, source)
  )`,
  `CREATE TABLE IF NOT EXISTS ml_feature_health_checks (
    check_date TEXT NOT NULL,
    check_key TEXT NOT NULL,
    status TEXT NOT NULL,
    expected_date TEXT,
    actual_date TEXT,
    expected_count INTEGER,
    actual_count INTEGER,
    payload_json TEXT NOT NULL,
    computed_at INTEGER NOT NULL DEFAULT (unixepoch()),
    PRIMARY KEY (check_date, check_key)
  )`,
  `CREATE TABLE IF NOT EXISTS ml_pipeline_generations (
    market TEXT NOT NULL,
    pipeline TEXT NOT NULL,
    generation_version TEXT NOT NULL,
    status TEXT NOT NULL,
    baseline_source_date TEXT NOT NULL,
    baseline_start_date TEXT,
    last_delta_source_date TEXT NOT NULL,
    price_basis TEXT,
    feature_set TEXT NOT NULL,
    baseline_completed_at INTEGER NOT NULL,
    last_delta_completed_at INTEGER NOT NULL,
    payload_json TEXT NOT NULL DEFAULT '{}',
    updated_at INTEGER NOT NULL DEFAULT (unixepoch()),
    PRIMARY KEY (market, pipeline)
  )`,
  `CREATE TABLE IF NOT EXISTS turso_sync_runs (
    run_id TEXT PRIMARY KEY,
    mode TEXT NOT NULL,
    status TEXT NOT NULL,
    dry_run INTEGER NOT NULL DEFAULT 0,
    started_at INTEGER NOT NULL DEFAULT (unixepoch()),
    finished_at INTEGER,
    summary_json TEXT,
    error_message TEXT
  )`,
  `CREATE TABLE IF NOT EXISTS turso_sync_partitions (
    mode TEXT NOT NULL,
    table_name TEXT NOT NULL,
    partition_key TEXT NOT NULL,
    range_start TEXT,
    range_end TEXT,
    row_count INTEGER NOT NULL DEFAULT 0,
    status TEXT NOT NULL,
    run_id TEXT,
    synced_at INTEGER,
    error_message TEXT,
    PRIMARY KEY (mode, table_name, partition_key)
  )`,
  `CREATE INDEX IF NOT EXISTS turso_sync_partitions_status_idx ON turso_sync_partitions(mode, status, table_name)`,
  `CREATE TABLE IF NOT EXISTS fx_rates_daily (
    pair TEXT NOT NULL,
    date TEXT NOT NULL,
    rate REAL NOT NULL,
    source TEXT NOT NULL DEFAULT 'csv',
    imported_at INTEGER NOT NULL DEFAULT (unixepoch()),
    PRIMARY KEY (pair, date)
  )`,
  `CREATE INDEX IF NOT EXISTS fx_rates_daily_date_idx ON fx_rates_daily(date)`,
  `CREATE TABLE IF NOT EXISTS custom_charts (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    formula TEXT NOT NULL,
    formula_ast_json TEXT NOT NULL,
    mode TEXT NOT NULL DEFAULT 'valuation',
    base_date TEXT,
    display_currency TEXT NOT NULL DEFAULT 'LOCAL',
    missing_policy TEXT NOT NULL DEFAULT 'intersection',
    indicator_config_json TEXT NOT NULL,
    favorite INTEGER NOT NULL DEFAULT 0,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at INTEGER NOT NULL DEFAULT (unixepoch()),
    updated_at INTEGER NOT NULL DEFAULT (unixepoch())
  )`,
  `CREATE INDEX IF NOT EXISTS custom_charts_sort_idx ON custom_charts(favorite DESC, sort_order ASC, updated_at DESC)`,
]

/** 廃止されたテーブル。存在していれば DROP する（再実行しても無害）。 */
const DEPRECATED_DROPS: string[] = [
  `DROP TABLE IF EXISTS screener_snapshots`,
]

/** 既存テーブルに後から追加するカラム。重複エラーは握りつぶす。 */
const ADD_COLUMN_IF_MISSING: string[] = [
  `ALTER TABLE sector_master ADD COLUMN market_segment TEXT`,
  `ALTER TABLE sector_master ADD COLUMN sector33 TEXT`,
  `ALTER TABLE sector_master ADD COLUMN margin_type TEXT`,
  // Phase 3.6: 時価総額計算用
  `ALTER TABLE ticker_universe ADD COLUMN shares_outstanding INTEGER`,
  `ALTER TABLE ticker_universe ADD COLUMN shares_updated_at INTEGER`,
  // Phase 4: J-Quants /listed/info 由来の業種区分
  `ALTER TABLE ticker_universe ADD COLUMN sector17_code TEXT`,
  `ALTER TABLE ticker_universe ADD COLUMN sector17_name TEXT`,
  `ALTER TABLE ticker_universe ADD COLUMN sector33_code TEXT`,
  `ALTER TABLE ticker_universe ADD COLUMN sector33_name TEXT`,
  `ALTER TABLE ticker_universe ADD COLUMN market_segment TEXT`,
  `ALTER TABLE ticker_universe ADD COLUMN margin_code TEXT`,
  `ALTER TABLE ticker_universe ADD COLUMN margin_type TEXT`,
  // US: Tiingo調整OHLCをraw価格と分離して保持する
  `ALTER TABLE market_ohlcv_daily ADD COLUMN adj_open REAL`,
  `ALTER TABLE market_ohlcv_daily ADD COLUMN adj_high REAL`,
  `ALTER TABLE market_ohlcv_daily ADD COLUMN adj_low REAL`,
  `ALTER TABLE market_ohlcv_daily ADD COLUMN adj_volume INTEGER`,
  // US screener: latest-period metrics are computed once with the snapshot.
  `ALTER TABLE market_daily_snapshots ADD COLUMN prev_close REAL`,
  `ALTER TABLE market_daily_snapshots ADD COLUMN close_5d REAL`,
  `ALTER TABLE market_daily_snapshots ADD COLUMN close_20d REAL`,
  `ALTER TABLE market_daily_snapshots ADD COLUMN close_60d REAL`,
  `ALTER TABLE market_daily_snapshots ADD COLUMN close_120d REAL`,
  `ALTER TABLE market_daily_snapshots ADD COLUMN avg_volume_20 REAL`,
  `ALTER TABLE market_daily_snapshots ADD COLUMN ma_200 REAL`,
  `ALTER TABLE market_daily_snapshots ADD COLUMN ma_200_prev REAL`,
  `ALTER TABLE market_daily_snapshots ADD COLUMN ma_200_observations INTEGER`,
  // Phase 4: J-Quants + JPX 公式決算予定の表示補完
  `ALTER TABLE earnings_calendar ADD COLUMN company_name TEXT`,
  `ALTER TABLE earnings_calendar ADD COLUMN sector_name TEXT`,
  `ALTER TABLE earnings_calendar ADD COLUMN market_segment TEXT`,
  `ALTER TABLE earnings_calendar ADD COLUMN source TEXT`,
  `ALTER TABLE earnings_calendar ADD COLUMN source_url TEXT`,
  `ALTER TABLE earnings_calendar ADD COLUMN scheduled_time TEXT`,
  `ALTER TABLE earnings_calendar ADD COLUMN scheduled_time_kind TEXT`,
  `ALTER TABLE earnings_calendar ADD COLUMN scheduled_time_source TEXT`,
  `ALTER TABLE earnings_calendar ADD COLUMN scheduled_time_source_url TEXT`,
  `ALTER TABLE earnings_calendar ADD COLUMN predicted_time TEXT`,
  `ALTER TABLE earnings_calendar ADD COLUMN prediction_confidence TEXT`,
  `ALTER TABLE earnings_calendar ADD COLUMN prediction_sample_count INTEGER`,
  `ALTER TABLE earnings_calendar ADD COLUMN prediction_mode_count INTEGER`,
  `ALTER TABLE earnings_calendar ADD COLUMN actual_disclosed_date TEXT`,
  `ALTER TABLE earnings_calendar ADD COLUMN actual_disclosed_time TEXT`,
  `ALTER TABLE earnings_calendar ADD COLUMN actual_disclosed_at TEXT`,
  `ALTER TABLE earnings_calendar ADD COLUMN actual_source TEXT`,
  `ALTER TABLE earnings_calendar ADD COLUMN actual_source_url TEXT`,
  `ALTER TABLE earnings_calendar ADD COLUMN time_bucket TEXT`,
  `ALTER TABLE earnings_calendar ADD COLUMN time_updated_at INTEGER`,
  `CREATE INDEX IF NOT EXISTS earn_import_date_ticker_idx
    ON earnings_calendar(imported_at, announce_date, ticker)`,
  `CREATE INDEX IF NOT EXISTS earn_time_bucket_date_idx ON earnings_calendar(time_bucket, announce_date)`,
  `ALTER TABLE kabutan_material_news ADD COLUMN related_stocks_json TEXT NOT NULL DEFAULT '[]'`,
]

function isBusy(error: unknown): boolean {
  const message = error instanceof Error ? error.message : String(error)
  return /SQLITE_BUSY|database is locked/i.test(message)
}

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms))
}

async function executeSchemaSql(client: Client, sql: string): Promise<void> {
  const max = Number(process.env.SQLITE_BUSY_RETRIES ?? 8)
  for (let attempt = 0; ; attempt += 1) {
    try {
      await client.execute(sql)
      return
    } catch (error) {
      if (!isBusy(error) || attempt >= max) throw error
      await sleep(Math.min(2500, 120 * 2 ** attempt))
    }
  }
}

export async function ensureSchema(client: Client): Promise<void> {
  for (const sql of STATEMENTS) {
    await executeSchemaSql(client, sql)
  }
  for (const sql of DEPRECATED_DROPS) {
    try { await executeSchemaSql(client, sql) } catch { /* 無視 */ }
  }
  for (const sql of ADD_COLUMN_IF_MISSING) {
    try { await executeSchemaSql(client, sql) } catch (e) {
      const msg = (e as Error).message ?? ''
      if (!/duplicate column name/i.test(msg)) {
        // 致命的でないので警告のみ
        console.warn('[migrate] ADD COLUMN warning:', msg)
      }
    }
  }
}
